pub const PUZZLE_BLOCK_HEIGHT: usize = 3;
pub const PUZZLE_BLOCK_WIDTH: usize = 3;
pub const PUZZLE_DIMENTION: usize = PUZZLE_BLOCK_HEIGHT * PUZZLE_BLOCK_WIDTH;
pub const PUZZLE_TOTAL_CELL_COUNT: usize = PUZZLE_DIMENTION * PUZZLE_DIMENTION;
pub const PUZZLE_MAXIMUM_VALUE: u8 = PUZZLE_DIMENTION as u8;
