pub const PUZZLE_BLOCK_HEIGHT: usize = 3;
pub const PUZZLE_BLOCK_WIDTH: usize = 3;
pub const PUZZLE_DIMENTION: usize = PUZZLE_BLOCK_HEIGHT * PUZZLE_BLOCK_WIDTH;
pub const MAXIMUM_VALUE: u8 = PUZZLE_DIMENTION as u8;
