pub const PUZZLE_SUB_GRID_HEIGHT: usize = 3;
pub const PUZZLE_SUB_GRID_WIDTH: usize = 3;
pub const PUZZLE_DIMENTION: usize = PUZZLE_SUB_GRID_HEIGHT * PUZZLE_SUB_GRID_WIDTH;
pub const MAXIMUM_VALUE: u8 = (PUZZLE_SUB_GRID_HEIGHT * PUZZLE_SUB_GRID_WIDTH) as u8;
